"""Type stubs for beartype.roar module (exceptions)."""

class BeartypeException(Exception): ...
class BeartypeCallHintParamViolation(BeartypeException): ...
class BeartypeCallHintReturnViolation(BeartypeException): ...
